# Generated by Django 4.1 on 2022-08-20 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0034_alter_activemembers_image_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donation_date',
            field=models.DateField(default=datetime.date(2022, 8, 20)),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 8, 20)),
        ),
        migrations.AlterField(
            model_name='medicinestockmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 8, 20)),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_date',
            field=models.DateField(default=datetime.date(2022, 8, 20)),
        ),
    ]
